version: '3'
services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lnmp
    volumes:
      # project files
      - ./www/:/usr/share/nginx/html/
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      #- ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      #- ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      # log
      - ./log/nginx/:/var/log/nginx/

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - lnmp
    volumes:
      # NOTE: your data will be stored in ./mysql/data/
      # You can change the mysql storage location here
      - ./mysql/data/:/var/lib/mysql/
      # mysql configs
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_password

  php-fpm:
    build: ./php-fpm
    image: php-fpm:7.0
    container_name: php-fpm
    restart: always
    ports:
      - "9000:9000"
    networks:
      - lnmp
    volumes:
      # project files
      - ./www/:/usr/share/nginx/html/
      # Your php.ini
      - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
      # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=

networks:
  lnmp:
    driver: bridge
